
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: webapp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular-container
        image: angularproject.azurecr.io/angular-app1:0.0.1

        ports:
        - containerPort: 80
