trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy Angular app to AKS
  jobs:
  - deployment: DeployAngular
    displayName: 'Deploy Angular app'
    environment: 'aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: Kubernetes@1
            displayName: 'Apply Kubernetes manifests'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aks1'   # Your AKS service connection name
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: |
                deployment.yaml
                service.yaml
