# # trigger:
# #   branches:
# #     include:
# #       - main
 
# # stages:
# #   - stage: Deploy
# #     jobs:
# #       - job: DeployToK8s
# #         displayName: Deploy to Kubernetes
# #         pool:
# #           name: agentpool1
# #         steps:
# #           - script: |
# #               echo "Debugging files:"
# #               ls -l $(Build.SourcesDirectory)
# #             displayName: "List Source Directory"
 
# #           - task: KubernetesManifest@0
# #             displayName: Deploy to AKS
# #             inputs:
# #               action: deploy
# #               kubernetesServiceConnection: 'aks1'
# #               namespace: default
# #               manifests: |
# #                  $(Build.SourcesDirectory)/deployment.yaml 
# #                  $(Build.SourcesDirectory)/service.yaml





                


# trigger:
#   branches:
#     include:
#       - main

# variables:
#   dockerHubRepo: siddiqkesavansk/nginx
#   imageTag: latest

# jobs:
# - job: BuildAndPush
#   displayName: Build & Push Docker Image to Docker Hub
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: Docker@2
#     displayName: Build and push Docker image
#     inputs:
#       containerRegistry: 'dockerhub'   # Your Docker Hub service connection in Azure DevOps
#       repository: $(dockerHubRepo)
#       command: buildAndPush
#       Dockerfile: Dockerfile
#       tags: |
#         $(imageTag)

# - job: DeployToK8s
#   dependsOn: BuildAndPush
#   displayName: Deploy to Kubernetes
#   pool:
#     name: agentpool1   # Your self-hosted or hosted agent pool with kubectl configured
#   steps:
#   - script: |
#       # Update deployment.yaml image to the new image
#       sed -i "s|image:.*|image: $(dockerHubRepo):$(imageTag)|" $(Build.SourcesDirectory)/deployment.yaml

#       # Apply deployment and service
#       kubectl apply -f $(Build.SourcesDirectory)/deployment.yaml
#       kubectl apply -f $(Build.SourcesDirectory)/service.yaml
#     displayName: Deploy updated manifests to Kubernetes











# trigger:
#   branches:
#     include:
#       - main

# variables:
#   dockerHubRepo: siddiqkesavansk/nginx
#   imageTag: latest

# jobs:
# - job: BuildPushAndDeploy
#   displayName: Build, Push Docker Image and Deploy to Kubernetes
#   pool:
#     name: agentpool1   # Self-hosted agent pool with Docker and kubectl installed/configured

#   steps:
#   # Step 0: Checkout repo (Dockerfile is in repo)
#   - checkout: self

#   # Step 1: Enable Buildx (avoids legacy builder warning)
#   - script: |
#        docker buildx create --use
#        docker buildx inspect --bootstrap

#     displayName: Enable Docker Buildx

#   # Step 2: Build and push Docker image using Dockerfile from the repo root
#   - script: |
#       docker buildx build \
#         --platform linux/amd64 \
#         -f $(Build.SourcesDirectory)/Dockerfile \
#         -t $(dockerHubRepo):$(imageTag) \
#         --push $(Build.SourcesDirectory)
#     displayName: Build and Push Docker Image with Buildx

#   # Step 3: Update manifests and deploy to Kubernetes
#   - script: |
#       # Update deployment.yaml image to the new image
#       sed -i "s|image:.*|image: $(dockerHubRepo):$(imageTag)|" $(Build.SourcesDirectory)/deployment.yaml

#       # Apply deployment and service manifests
#       kubectl apply -f $(Build.SourcesDirectory)/deployment.yaml
#       kubectl apply -f $(Build.SourcesDirectory)/service.yaml
#     displayName: Deploy updated manifests to Kubernetes

trigger:
  branches:
    include:
      - main

variables:
  dockerHubRepo: siddiqkesavansk/nginx
  imageTag: v1

jobs:
- job: BuildPushAndPush
  displayName: Build and Push Docker Image
  pool:
    name: agentpool1
  steps:
  - checkout: self
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: 'dockerhub'
      repository: $(dockerHubRepo)
      command: buildAndPush
      Dockerfile: Dockerfile
      tags: |
        $(imageTag)

- job: DeployToK8s
  displayName: Deploy to Kubernetes
  dependsOn: BuildPushAndPush
  pool:
    name: agentpool1
  steps:
  - script: |
      echo "Showing deployment.yaml BEFORE image replacement:"
      cat $(Build.SourcesDirectory)/deployment.yaml
    displayName: Show deployment.yaml before sed

  - script: |
      sed -i "s|image:.*|image: $(dockerHubRepo):$(imageTag)|" $(Build.SourcesDirectory)/deployment.yaml
    displayName: Update deployment image

  - script: |
      echo "Showing deployment.yaml AFTER image replacement:"
      cat $(Build.SourcesDirectory)/deployment.yaml
    displayName: Show deployment.yaml after sed

  - task: KubernetesManifest@1
    displayName: Deploy to AKS
    inputs:
      action: deploy
      kubernetesServiceConnection: 'aks1'
      namespace: default
      manifests: |
        $(Build.SourcesDirectory)/deployment.yaml
        $(Build.SourcesDirectory)/service.yaml
      containers:
        $(imageFullName)

      






