trigger:
  branches:
    include:
      - main

pool:
  name: agentpool1
  demands:
    - agent.os -equals Linux


stages:
- stage: Deploy
  displayName: Deploy Angular app to AKS
  jobs:
  - deployment: DeployAngular
    displayName: 'Deploy Angular app'
    environment: 'aks1'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

- script: ls -l
  displayName: 'List files in repo root'

          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aks1'   # Your AKS service connection name
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: |
                deployment.yaml
                service.yaml




                


