
trigger:
  branches:
    include:
      - main
 
stages:
  - stage: Deploy
    jobs:
      - job: DeployToK8s
        displayName: Deploy to Kubernetes
        pool:
          name: agentpool1
        steps:
          - script: |
              echo "Debugging files:"
              ls -l $(Build.SourcesDirectory)
            displayName: "List Source Directory"
 
          - task: KubernetesManifest@0
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: 'aks1'
              namespace: webapp-prod
              manifests: |
                $(Build.SourcesDirectory)/k8s/deployment.yaml
                $(Build.SourcesDirectory)/k8s/service.yaml




                


